# Conexión a la Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/pdf_reader
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

#Ejecutar schema.sql al iniciar la aplicación
spring.sql.init.mode=always

# CONFIGURACIÓN DE EMERGENCIA PARA EVITAR EL BLOQUEO DE METADATOS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Configuración del Almacén de Vectores (Sintaxis para Spring AI 2.0.0-M8)
spring.ai.vectorstore.pgvector.common.table-name=vector_documentos
spring.ai.vectorstore.pgvector.common.dimensions=768
spring.ai.vectorstore.pgvector.initialize-schema=false

# Modelo de embeddings de Ollama
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.ollama.chat.model=llama3:latest 