#Nombre de la aplicacion
spring.application.name=pdf-reader

# Configuracion de Postgre

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# configuracion JPA

#crear tablas autoamticamente si no existen
spring.jpa.hibernate.ddl-auto=update
#mostar comandos cuando se ejecuten
spring.jpa.show-sql=true

#Configuracion IA

#puerto a usar
spring.ai.ollama.base-url=http://localhost:11434
#modelo de lenguaje
spring.ai.ollama.chat.model=llama3